version: '3'
services:
  user:
    build:
      context: ./userService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user_database
  user_database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
